### ISSUE TITLE
AdminProject1 is able to interact with Things that belongs to Project2

### ISSUE THREAD

**Issue by DanielBertocci** [hylkevds/FROST-Server.Plugin.SecurityTest#1]
I started from a clean installation of clean installation with docker compose and I provisioned with the batch request you provided in the scripts folder.
If I use the credential of AdminProject1 I can see the list of all users and interact with entities that do not belong to the assigned project.

During the startup of FROST indeed some error occur, like:
```
13:13:43.413 INFO           d.f.i.i.f.p.m.PluginModelLoader - Loading security definition from /usr/local/tomcat/webapps/FROST-Server/WEB-INF/data/model/secThings.json
scripts-web-1                    | 13:13:43.416 ERROR          d.f.i.i.f.p.m.PluginModelLoader - Failed to load model definition
scripts-web-1                    | com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "checkType" (class de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.CheckUserHasRoles), not marked as ignorable (2 known properties: "vheckType", "roles"])
scripts-web-1                    |  at [Source: (String)"{
scripts-web-1                    |   "entries": [
scripts-web-1                    |     {
scripts-web-1                    |       "tableName": "THINGS",
scripts-web-1                    |       "wrappers": [
scripts-web-1                    |         {
scripts-web-1                    |           "@class": "de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.ValidatorCUD",
scripts-web-1                    |           "checkInsert": {
scripts-web-1                    |             "@class": "de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.CheckMulti",
scripts-web-1                    |             "combineType": "OR",
scripts-web-1                    |             "subChecks": [
scripts-web-1                    |               {
scripts-web-1                    |                 "@class": "de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.CheckU"[truncated 3120 chars]; line: 14, column: 31] (through reference chain: de.fraunhofer.iosb.ilt.frostserver.util.SecurityModel["entries"]->java.util.ArrayList[0]->de.fraunhofer.iosb.ilt.frostserver.util.SecurityModel$SecurityEntry["wrappers"]->java.util.ArrayList[0]->de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.ValidatorCUD["checkInsert"]->de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.CheckMulti["subChecks"]->java.util.ArrayList[0]->de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.utils.validator.CheckUserHasRoles["checkType"])
scripts-web-1                    |      at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
```

I am not familiar with the configurations like secThings.json, I can understand the meaning of various settings but not accurately how they are mapped in the code.
Could you suggest some resources to learn a little more about the topic?

I would like to develop also a plugin for Oauth2/OpenID authentication and if you have any suggestion from where to start it would be great :-)

**Comment by DanielBertocci** [comment]
It seems to be a typo at
https://github.com/FraunhoferIOSB/FROST-Server/blob/723d4c63bc19d27d7a0fa33a03acca75bb83e3c4/FROST-Server.SQLjooq/src/main/java/de/fraunhofer/iosb/ilt/frostserver/persistence/pgjooq/utils/validator/CheckUserHasRoles.java#L73

**Comment by DanielBertocci** [comment]
I was able to solve the problem: it seems to be a problems related to hylkevds/frost-http-securitytest:latest.

- I changed the docker-compose.yaml to use the local Docker Image

- I changed the docker to use:
`FROM fraunhoferiosb/frost-server-http:latest` instead of `FROM fraunhoferiosb/frost-server-http:develop-2.x-2.2.0-SNAPSHOT`

Using your existing example I was able to fix a small issue on DELETE of a project: I got 400 instead of 403.

I will send you a PR with few changes

**Comment by hylkevds** [comment]
Yes, there was a typo at that exact spot that I fixed 5 days ago. It seems the Docker Image of this project still used the old FROST docker image.
I've triggered a rebuild, can you try again once that build is through?

**Comment by hylkevds** [comment]
There is no documentation for the fine-grained security extensions yet, that is all still very new.

Implementing OpenID should not be hard to do, using the Keycloak Auth module as an example.

**Comment by DanielBertocci** [comment]
> Yes, there was a typo at that exact spot that I fixed 5 days ago. It seems the Docker Image of this project still used the old FROST docker image. I've triggered a rebuild, can you try again once that build is through?

I wasn't able to identify the reason, but with a clean setup I have still problems to run the project. In the PR #2  I sent you though, everything works smooth.

**Comment by hylkevds** [comment]
The problem was that the container image at DockerHub was built using an old FROST-HTTP image. The rebuild fixed that. No need to change anything here.
